%% 2D Advection-Diffusion: FOM Snapshots -> POD Basis -> POD-Galerkin ROM
%
% Solves:  dC/dt + u*dC/dx + v*dC/dy = D*(d2C/dx2 + d2C/dy2)
%
% Pipeline:
%   1) Run the full-order model (FOM) with explicit Euler,
%      C_vec = C_vec + dt*(A*C_vec), storing snapshots C(t_k) as columns
%      of a snapshot matrix X.
%   2) Compute a POD basis Phi (r leading left singular vectors of X,
%      i.e. via the SVD -- the "method of snapshots").
%   3) Project the FOM operator A onto the POD subspace to build a small
%      r x r POD-Galerkin ROM:  da/dt = A_r*a + b_r,  A_r = Phi'*A*Phi.
%   4) March the ROM forward in time (same explicit Euler rule, same dt)
%      and reconstruct C_ROM(t) = Phi*a(t) + mean.
%   5) Compare C_ROM(t) against the FOM snapshots: relative L2 error,
%      singular value decay / energy captured, and field snapshots.
%
% Author: Generated by Claude
% -------------------------------------------------------------------

clear; clc; close all;

%% ------------------- User-defined parameters -----------------------
Lx = 2.0;          % domain length in x [m]
Ly = 2.0;          % domain length in y [m]
Nx = 61;           % number of grid points in x  (kept modest so the
Ny = 61;           % number of grid points in y   snapshot matrix stays small)

D  = 0.01;         % diffusion coefficient [m^2/s]
u  = 1.0;          % advection velocity in x [m/s]
% v  = 0.5;          % advection velocity in y [m/s]
v  = 0.77;          % advection velocity in y [m/s]

% T_final = 1.0;     % total simulation time [s]
T_final = 10.0;     % total simulation time [s]

% use_upwind = true; % true -> 1st-order upwind for advection
use_upwind = false; % true -> 1st-order upwind for advection
bc_type = 'periodic';   % 'dirichlet' or 'periodic'

% --- POD / ROM specific parameters ---
snapshot_stride  = 10;      % store every k-th FOM time step as a snapshot
% subtract_mean    = true;   % POD on fluctuations about the temporal mean
subtract_mean    = false;   % POD on fluctuations about the temporal mean
% r_modes          = 12;     % number of POD modes to keep in the ROM
r_modes          = 40;     % number of POD modes to keep in the ROM
                            % (set to [] to instead pick r from energy_threshold)
energy_threshold = 0.9999; % used only if r_modes = []

plot_every = 20;    % FOM field plot update frequency (in time steps)

% nu = 1;
dx = Lx/Nx;
nu = dx*u/2;
% nu = 0;

%% ------------------- Grid setup --------------------------------------
if strcmp(bc_type, 'periodic')
    x = linspace(0, Lx, Nx+1); x(end) = [];
    y = linspace(0, Ly, Ny+1); y(end) = [];
else
    x = linspace(0, Lx, Nx);
    y = linspace(0, Ly, Ny);
end
dx = x(2) - x(1);
dy = y(2) - y(1);
[X, Y] = meshgrid(x, y);   % Ny x Nx
Ndof = Nx*Ny;

%% ------------------- Initial condition --------------------------------
x0 = 0.5*Lx; y0 = 0.5*Ly;
sigma = 0.08*Lx;
C = exp(-((X - x0).^2 + (Y - y0).^2) / (2*sigma^2));
C0_field = C;

%% ------------------- Stability-based time step -------------------------
dt_diff = (dx^2 * dy^2) / (2*D*(dx^2 + dy^2));
dt_adv  = 1 / (abs(u)/dx + abs(v)/dy);
dt = 0.5 * min(dt_diff, dt_adv);
Nt = ceil(T_final/dt);
dt = T_final/Nt;

fprintf('Grid: %d x %d (Ndof = %d),  dx = %.4g, dy = %.4g\n', Nx, Ny, Ndof, dx, dy);
fprintf('BC type: %s,  dt = %.4g,  Nt = %d steps\n', bc_type, dt, Nt);

%% ------------------- Assemble FOM operator A ----------------------------
is_periodic = strcmp(bc_type, 'periodic');

D2x = build_D2(Nx, dx, is_periodic);
D2y = build_D2(Ny, dy, is_periodic);
if use_upwind
    D1x = build_D1_upwind(Nx, dx, u, is_periodic);
    D1y = build_D1_upwind(Ny, dy, v, is_periodic);
else
    D1x = build_D1_central(Nx, dx, is_periodic);
    D1y = build_D1_central(Ny, dy, is_periodic);
end

Ix = speye(Nx); Iy = speye(Ny);

A = -u*kron(D1x, Iy) - v*kron(Ix, D1y) + nu*(D*(kron(D2x, Iy) + kron(Ix, D2y)));

if strcmp(bc_type, 'dirichlet')
    [Igrid, Jgrid] = ndgrid(1:Ny, 1:Nx);
    boundary_mask = (Igrid==1)|(Igrid==Ny)|(Jgrid==1)|(Jgrid==Nx);
    boundary_idx = find(boundary_mask(:));
    A(boundary_idx,:) = 0;
    C0_field(boundary_mask) = 0;
    C = C0_field;
end

C0_vec = C(:);

%% ============================================================
%  STEP 1: FOM simulation with snapshot storage
%  ============================================================
n_snap_est = floor(Nt/snapshot_stride) + 1;
Xsnap  = zeros(Ndof, n_snap_est);
t_snap = zeros(1, n_snap_est);

C_vec = C0_vec;
Xsnap(:,1)  = C_vec;
t_snap(1)   = 0;
isnap = 1;

figure('Color','w','Position',[80 80 850 650]);
tic;
for n = 1:Nt
    C_vec = C_vec + dt*(A*C_vec);

    if mod(n, snapshot_stride) == 0
        isnap = isnap + 1;
        Xsnap(:,isnap)  = C_vec;
        t_snap(isnap)   = n*dt;
    end

    if mod(n, plot_every) == 0 || n == Nt
        surf(X, Y, reshape(C_vec,Ny,Nx), 'EdgeColor','none');
        view(2); shading interp; colorbar; axis equal tight;
        xlabel('x'); ylabel('y');
        title(sprintf('FOM,  t = %.3f s  (step %d/%d)', n*dt, n, Nt));
        caxis([0 max(C0_vec)]);
        drawnow;
    end
end
t_fom = toc;
Xsnap  = Xsnap(:, 1:isnap);
t_snap = t_snap(1:isnap);
n_snap = isnap;

fprintf('FOM simulation done: %d snapshots stored. FOM wall time = %.3fs\n', n_snap, t_fom);

%% ============================================================
%  STEP 2: Compute POD basis via SVD of the snapshot matrix
%  ============================================================
if subtract_mean
    Cmean = mean(Xsnap, 2);
else
    Cmean = zeros(Ndof,1);
end
Xc = Xsnap - Cmean;

[Phi_full, Sigma, ~] = svd(Xc, 'econ');
sigma = diag(Sigma);
energy = cumsum(sigma.^2) / sum(sigma.^2);

if isempty(r_modes)
    r = find(energy >= energy_threshold, 1, 'first');
else
    r = min(r_modes, numel(sigma));
end
Phi = Phi_full(:, 1:r);

fprintf('POD: kept r = %d modes, capturing %.6f%% of snapshot energy\n', r, 100*energy(r));

%% ============================================================
%  STEP 3: Project FOM operator onto POD subspace (Galerkin ROM)
%  ============================================================
%   dC/dt = A*C ,   C = Phi*a + Cmean
%   => Phi'*Phi * da/dt = Phi'*A*(Phi*a + Cmean)      (Phi'*Phi = I_r)
%   => da/dt = (Phi'*A*Phi)*a + Phi'*A*Cmean  =:  A_r*a + b_r
A_r = Phi' * (A * Phi);   % r x r, dense
b_r = Phi' * (A * Cmean); % r x 1  (zero if subtract_mean = false)

a0 = Phi' * (C0_vec - Cmean);

%% ============================================================
%  STEP 4: March the ROM forward with the SAME explicit Euler rule
%  ============================================================
a = a0;
Asnap  = zeros(r, n_snap);
Asnap(:,1) = a;
isnap = 1;

tic;
for n = 1:Nt
    a = a + dt*(A_r*a + b_r);
    if mod(n, snapshot_stride) == 0
        isnap = isnap + 1;
        Asnap(:,isnap) = a;
    end
end
t_rom = toc;

fprintf('ROM simulation done (r=%d). ROM wall time = %.3fs  (speedup x%.1f)\n', ...
        r, t_rom, t_fom/t_rom);

%% ============================================================
%  STEP 5: Reconstruct ROM states and compare to FOM snapshots
%  ============================================================
Xrom = Phi*Asnap + Cmean;   % Ndof x n_snap reconstructed field history

rel_err = zeros(1, n_snap);
for k = 1:n_snap
    rel_err(k) = norm(Xrom(:,k) - Xsnap(:,k)) / norm(Xsnap(:,k));
end

fprintf('Relative L2 error: max = %.3e, final-time = %.3e\n', max(rel_err), rel_err(end));

%% ------------------- Diagnostic plots ------------------------------------
figure('Color','w','Position',[950 80 850 650]);

subplot(2,2,1);
semilogy(sigma, 'o-','LineWidth',1.2); grid on;
xlabel('mode index'); ylabel('\sigma_i');
title('POD singular value decay');
xline(r, 'r--', sprintf('r = %d', r));

subplot(2,2,2);
plot(energy, 'o-', 'LineWidth',1.2); grid on; hold on;
yline(energy(r), 'r--');
xline(r, 'r--');
xlabel('number of modes r'); ylabel('cumulative energy');
title('POD energy captured');
ylim([0 1.01]);

subplot(2,2,3);
semilogy(t_snap, rel_err, 'LineWidth', 1.5); grid on;
xlabel('t'); ylabel('||C_{ROM}-C_{FOM}||_2 / ||C_{FOM}||_2');
title(sprintf('ROM relative error (r = %d modes)', r));

subplot(2,2,4);
Cfinal_fom = reshape(Xsnap(:,end), Ny, Nx);
Cfinal_rom = reshape(Xrom(:,end),  Ny, Nx);
err_field  = abs(Cfinal_fom - Cfinal_rom);
surf(X, Y, err_field, 'EdgeColor','none'); view(2); shading interp; colorbar;
axis equal tight; xlabel('x'); ylabel('y');
title(sprintf('|C_{FOM}-C_{ROM}| at t = %.2f', t_snap(end)));

%% ------------------- FOM vs ROM field comparison at final time -----------
% figure('Color','w','Position',[80 750 1200 420]);
figure('Color','w');
subplot(1,3,1);
surf(X, Y, Cfinal_fom, 'EdgeColor','none'); view(2); shading interp; colorbar;
axis equal tight; title('FOM (full order)'); xlabel('x'); ylabel('y');

subplot(1,3,2);
surf(X, Y, Cfinal_rom, 'EdgeColor','none'); view(2); shading interp; colorbar;
axis equal tight; title(sprintf('POD-Galerkin ROM (r=%d)', r)); xlabel('x'); ylabel('y');

subplot(1,3,3);
surf(X, Y, err_field, 'EdgeColor','none'); view(2); shading interp; colorbar;
axis equal tight; title('Absolute error'); xlabel('x'); ylabel('y');


%% ===================== Local helper functions ===========================
function D2 = build_D2(N, h, periodic)
    D2 = spdiags(ones(N,1)*[1 -2 1]/h^2, -1:1, N, N);
    if periodic
        D2(1, N) = 1/h^2;
        D2(N, 1) = 1/h^2;
    end
end

function D1 = build_D1_upwind(N, h, vel, periodic)
    if vel >= 0
        D1 = spdiags(ones(N,1)*[-1 1]/h, -1:0, N, N);
        if periodic
            D1(1, N) = -1/h;
        end
    else
        D1 = spdiags(ones(N,1)*[-1 1]/h, 0:1, N, N);
        if periodic
            D1(N, 1) = 1/h;
        end
    end
end

function D1 = build_D1_central(N, h, periodic)
    D1 = spdiags(ones(N,1)*[-1 1]/(2*h), [-1 1], N, N);
    if periodic
        D1(1, N) = -1/(2*h);
        D1(N, 1) =  1/(2*h);
    end
end