%% 2D Advection-Diffusion Equation Solver (Explicit Euler, Matrix Form)
%
% Solves:  dC/dt + u*dC/dx + v*dC/dy = D*(d2C/dx2 + d2C/dy2)
%
% The spatial discretization is assembled ONCE into a single sparse
% matrix A, so that every explicit Euler update is simply:
%
%           C_vec = C_vec + dt * (A * C_vec)
%
% where C_vec = C(:) is the vectorized concentration field.
%
% Supports two boundary condition options (set bc_type below):
%   'dirichlet' -> C = 0 fixed on the boundary
%   'periodic'  -> wrap-around BC (domain tiles seamlessly)
%
% Author: Generated by Claude
% -------------------------------------------------------------------

clear; clc; close all;

%% ------------------- User-defined parameters -----------------------
Lx = 2.0;          % domain length in x [m]
Ly = 2.0;          % domain length in y [m]
Nx = 101;          % number of grid points in x
Ny = 101;          % number of grid points in y

D  = 0.01;         % diffusion coefficient [m^2/s]
u  = 1.0;          % advection velocity in x [m/s]
v  = 0.5;          % advection velocity in y [m/s]

T_final = 1.0;     % total simulation time [s]

use_upwind = true; % true -> 1st-order upwind for advection (more stable)
                    % false -> 2nd-order central differences

bc_type = 'periodic';   % 'dirichlet' or 'periodic'

plot_every = 10;    % plot update frequency (in time steps)

%% ------------------- Grid setup --------------------------------------
% NOTE: for periodic BCs, x=0 and x=Lx (resp. y=0,Ly) represent the SAME
% physical point, so we generate Nx (Ny) points spanning [0, Lx) and use
% dx = Lx/Nx (not Lx/(Nx-1)) to keep spacing uniform around the wrap.
if strcmp(bc_type, 'periodic')
    x = linspace(0, Lx, Nx+1); x(end) = [];
    y = linspace(0, Ly, Ny+1); y(end) = [];
else
    x = linspace(0, Lx, Nx);
    y = linspace(0, Ly, Ny);
end
dx = x(2) - x(1);
dy = y(2) - y(1);

[X, Y] = meshgrid(x, y);   % X, Y are Ny x Nx, C(i,j) = C(y_i, x_j)

%% ------------------- Initial condition --------------------------------
x0 = 0.5*Lx; y0 = 0.5*Ly;
sigma = 0.08*Lx;
C = exp(-((X - x0).^2 + (Y - y0).^2) / (2*sigma^2));
C0 = C;   % keep a copy for comparison/plotting

%% ------------------- Stability-based time step -------------------------
dt_diff = (dx^2 * dy^2) / (2*D*(dx^2 + dy^2));
dt_adv  = 1 / (abs(u)/dx + abs(v)/dy);

safety_factor = 0.5;
dt = safety_factor * min(dt_diff, dt_adv);

Nt = ceil(T_final/dt);
dt = T_final/Nt;

fprintf('Grid: %d x %d,  dx = %.4g, dy = %.4g\n', Nx, Ny, dx, dy);
fprintf('BC type: %s\n', bc_type);
fprintf('Diffusion dt limit = %.4g,  Advection dt limit = %.4g\n', dt_diff, dt_adv);
fprintf('Using dt = %.4g,  Nt = %d steps,  T_final = %.4g\n', dt, Nt, T_final);

%% ------------------- Assemble 1D operator matrices ----------------------
is_periodic = strcmp(bc_type, 'periodic');

D2x = build_D2(Nx, dx, is_periodic);
D2y = build_D2(Ny, dy, is_periodic);

if use_upwind
    D1x = build_D1_upwind(Nx, dx, u, is_periodic);
    D1y = build_D1_upwind(Ny, dy, v, is_periodic);
else
    D1x = build_D1_central(Nx, dx, is_periodic);
    D1y = build_D1_central(Ny, dy, is_periodic);
end

%% ------------------- Assemble full 2D operator A ------------------------
% For C stored as (Ny x Nx) and vectorized column-major as C(:):
%   operator acting in x (columns)  -> kron(Dx, I_Ny)
%   operator acting in y (rows)     -> kron(I_Nx, Dy)
%
% dC/dt = -u*dC/dx - v*dC/dy + D*(d2C/dx2 + d2C/dy2)  =  A * C(:)

Ix = speye(Nx);
Iy = speye(Ny);

A = -u * kron(D1x, Iy) ...
    -v * kron(Ix, D1y) ...
    +D * ( kron(D2x, Iy) + kron(Ix, D2y) );

%% ------------------- Enforce Dirichlet BC (if selected) -----------------
% Dirichlet: C = 0 fixed on the boundary. Zero the corresponding rows of
% A so those entries never change (they must be initialized to 0).
% Periodic: no boundary rows to modify -- wrap-around is already baked
% into D1x/D1y/D2x/D2y via their corner entries.
if strcmp(bc_type, 'dirichlet')
    [Igrid, Jgrid] = ndgrid(1:Ny, 1:Nx);
    boundary_mask = (Igrid == 1) | (Igrid == Ny) | (Jgrid == 1) | (Jgrid == Nx);
    boundary_idx = find(boundary_mask(:));

    A(boundary_idx, :) = 0;

    C0(boundary_mask) = 0;   % initial condition must satisfy the BC
    C = C0;
end

%% ------------------- Time-stepping loop (matrix form) --------------------
C_vec = C(:);          % vectorize the field: C_vec = C(:)

figure('Color','w','Position',[100 100 800 650]);

t = 0;
for n = 1:Nt

    % ---- The core explicit Euler update ----
    C_vec = C_vec + dt * (A * C_vec);
    % -----------------------------------------

    t = t + dt;

    if mod(n, plot_every) == 0 || n == Nt
        C = reshape(C_vec, Ny, Nx);
        clf;
        surf(X, Y, C, 'EdgeColor', 'none');
        view(2); shading interp; colorbar;
        axis equal tight;
        xlabel('x'); ylabel('y');
        title(sprintf('2D Advection-Diffusion (%s BC),  t = %.3f s  (step %d/%d)', bc_type, t, n, Nt));
        caxis([0 max(C0(:))]);
        drawnow;
    end
end

C = reshape(C_vec, Ny, Nx);
fprintf('Simulation complete. Final time t = %.4g s\n', t);

%% ------------------- Optional: compare initial vs final ----------------
figure('Color','w');
subplot(1,2,1);
surf(X, Y, C0, 'EdgeColor','none'); view(2); shading interp; colorbar;
axis equal tight; title('Initial condition'); xlabel('x'); ylabel('y');

subplot(1,2,2);
surf(X, Y, C, 'EdgeColor','none'); view(2); shading interp; colorbar;
axis equal tight; title(sprintf('Final field, t = %.3f s', t)); xlabel('x'); ylabel('y');


%% ===================== Local helper functions ===========================
function D2 = build_D2(N, h, periodic)
    % Second-derivative (diffusion) matrix, 2nd-order central.
    D2 = spdiags(ones(N,1)*[1 -2 1]/h^2, -1:1, N, N);
    if periodic
        D2(1, N) = 1/h^2;   % wrap: point before index 1 is index N
        D2(N, 1) = 1/h^2;   % wrap: point after index N is index 1
    end
    % (if not periodic, boundary rows are meaningless here and are
    %  overwritten/ignored by the Dirichlet handling in the main script)
end

function D1 = build_D1_upwind(N, h, vel, periodic)
    % First-derivative (advection) matrix, 1st-order upwind.
    if vel >= 0
        D1 = spdiags(ones(N,1)*[-1 1]/h, -1:0, N, N);   % backward diff
        if periodic
            D1(1, N) = -1/h;   % wrap: point before index 1 is index N
        end
    else
        D1 = spdiags(ones(N,1)*[-1 1]/h, 0:1, N, N);    % forward diff
        if periodic
            D1(N, 1) = 1/h;    % wrap: point after index N is index 1
        end
    end
end

function D1 = build_D1_central(N, h, periodic)
    % First-derivative (advection) matrix, 2nd-order central.
    D1 = spdiags(ones(N,1)*[-1 1]/(2*h), [-1 1], N, N);
    if periodic
        D1(1, N) = -1/(2*h);
        D1(N, 1) =  1/(2*h);
    end
end