%% 2D Advection-Diffusion: FOM Snapshots -> POD Basis -> POD-Galerkin ROM
%
% Solves:  dC/dt + u*dC/dx + v*dC/dy = D*(d2C/dx2 + d2C/dy2)
%
% Pipeline:
%   1) Run the full-order model (FOM) with explicit Euler,
%      C_vec = C_vec + dt*(A*C_vec), storing snapshots C(t_k) as columns
%      of a snapshot matrix X.
%   2) Compute a POD basis Phi (r leading left singular vectors of X,
%      i.e. via the SVD -- the "method of snapshots").
%   3) Project the FOM operator A onto the POD subspace to build a small
%      r x r POD-Galerkin ROM:  da/dt = A_r*a + b_r,  A_r = Phi'*A*Phi.
%   4) March the ROM forward in time (same explicit Euler rule, same dt)
%      and reconstruct C_ROM(t) = Phi*a(t) + mean.
%   5) Compare C_ROM(t) against the FOM snapshots: relative L2 error,
%      singular value decay / energy captured, and field snapshots.
%
% Author: Generated by Claude
% -------------------------------------------------------------------

% clear; clc; close all;

%% ------------------- User-defined parameters -----------------------
Lx = 2.0;          % domain length in x [m]
Ly = 2.0;          % domain length in y [m]
Nx = 61;           % number of grid points in x  (kept modest so the
Ny = 61;           % number of grid points in y   snapshot matrix stays small)

D  = 0.01;         % diffusion coefficient [m^2/s]
u  = 1.0;          % advection velocity in x [m/s]
% v  = 0.5;          % advection velocity in y [m/s]
v  = 0.77;          % advection velocity in y [m/s]

% T_final = 1.0;     % total simulation time [s]
T_final = 10.0;     % total simulation time [s]

% use_upwind = true; % true -> 1st-order upwind for advection
use_upwind = false; % true -> 1st-order upwind for advection
bc_type = 'periodic';   % 'dirichlet' or 'periodic'

% --- POD / ROM specific parameters ---
snapshot_stride  = 10;      % store every k-th FOM time step as a snapshot
% subtract_mean    = true;   % POD on fluctuations about the temporal mean
subtract_mean    = false;   % POD on fluctuations about the temporal mean
r_modes          = 12;     % number of POD modes to keep in the ROM
                            % (set to [] to instead pick r from energy_threshold)
energy_threshold = 0.9999; % used only if r_modes = []

plot_every = 20;    % FOM field plot update frequency (in time steps)

%% ------------------- Grid setup --------------------------------------
if strcmp(bc_type, 'periodic')
    x = linspace(0, Lx, Nx+1); x(end) = [];
    y = linspace(0, Ly, Ny+1); y(end) = [];
else
    x = linspace(0, Lx, Nx);
    y = linspace(0, Ly, Ny);
end
dx = x(2) - x(1);
dy = y(2) - y(1);
[X, Y] = meshgrid(x, y);   % Ny x Nx
Ndof = Nx*Ny;

%% ------------------- Initial condition --------------------------------
x0 = 0.5*Lx; y0 = 0.5*Ly;
sigma = 0.08*Lx;
C = exp(-((X - x0).^2 + (Y - y0).^2) / (2*sigma^2));
C0_field = C;

%% ------------------- Stability-based time step -------------------------
dt_diff = (dx^2 * dy^2) / (2*D*(dx^2 + dy^2));
dt_adv  = 1 / (abs(u)/dx + abs(v)/dy);
dt = 0.5 * min(dt_diff, dt_adv);
Nt = ceil(T_final/dt);
dt = T_final/Nt;

fprintf('Grid: %d x %d (Ndof = %d),  dx = %.4g, dy = %.4g\n', Nx, Ny, Ndof, dx, dy);
fprintf('BC type: %s,  dt = %.4g,  Nt = %d steps\n', bc_type, dt, Nt);

%% ------------------- Assemble FOM operator A ----------------------------
is_periodic = strcmp(bc_type, 'periodic');

D2x = build_D2(Nx, dx, is_periodic);
D2y = build_D2(Ny, dy, is_periodic);
if use_upwind
    D1x = build_D1_upwind(Nx, dx, u, is_periodic);
    D1y = build_D1_upwind(Ny, dy, v, is_periodic);
else
    D1x = build_D1_central(Nx, dx, is_periodic);
    D1y = build_D1_central(Ny, dy, is_periodic);
end

Ix = speye(Nx); Iy = speye(Ny);
nu = 1;
% nu = 0;
A = -u*kron(D1x, Iy) - v*kron(Ix, D1y) + nu*(D*(kron(D2x, Iy) + kron(Ix, D2y)));

if strcmp(bc_type, 'dirichlet')
    [Igrid, Jgrid] = ndgrid(1:Ny, 1:Nx);
    boundary_mask = (Igrid==1)|(Igrid==Ny)|(Jgrid==1)|(Jgrid==Nx);
    boundary_idx = find(boundary_mask(:));
    A(boundary_idx,:) = 0;
    C0_field(boundary_mask) = 0;
    C = C0_field;
end

C0_vec = C(:);


%% ===================== Local helper functions ===========================
function D2 = build_D2(N, h, periodic)
    D2 = spdiags(ones(N,1)*[1 -2 1]/h^2, -1:1, N, N);
    if periodic
        D2(1, N) = 1/h^2;
        D2(N, 1) = 1/h^2;
    end
end

function D1 = build_D1_upwind(N, h, vel, periodic)
    if vel >= 0
        D1 = spdiags(ones(N,1)*[-1 1]/h, -1:0, N, N);
        if periodic
            D1(1, N) = -1/h;
        end
    else
        D1 = spdiags(ones(N,1)*[-1 1]/h, 0:1, N, N);
        if periodic
            D1(N, 1) = 1/h;
        end
    end
end

function D1 = build_D1_central(N, h, periodic)
    D1 = spdiags(ones(N,1)*[-1 1]/(2*h), [-1 1], N, N);
    if periodic
        D1(1, N) = -1/(2*h);
        D1(N, 1) =  1/(2*h);
    end
end