%% 1D Advection-Diffusion Equation Solver
%  Periodic BCs | Central differences | Energy-conserving time discretization
%
% Solves:  dC/dt + u*dC/dx = D*d2C/dx2 ,   x in [0, L), periodic
%
% SPATIAL DISCRETIZATION
%   Advection : central difference  ->  matrix D1 is SKEW-SYMMETRIC
%               (D1' = -D1 on a periodic grid). This matters because a
%               skew-symmetric operator satisfies C'*D1*C = 0 for any C,
%               i.e. it moves "energy" (the L2 norm) around in space but
%               never creates or destroys it -- exactly like the
%               continuous advection term.
%   Diffusion : standard central 2nd difference -> matrix D2 is
%               SYMMETRIC NEGATIVE SEMI-DEFINITE, which is what
%               physically dissipates energy.
%
% TIME DISCRETIZATION (the "energy-conserving" part)
%   Explicit Euler applied to a skew-symmetric system is unconditionally
%   UNSTABLE (energy grows every step, no matter how small dt is).
%   Instead we use the trapezoidal rule (Crank-Nicolson):
%
%       C^{n+1} = C^n + (dt/2) * A * (C^n + C^{n+1})
%       =>  (I - dt/2*A) C^{n+1} = (I + dt/2*A) C^n
%
%   The update matrix M = (I - dt/2*A)^{-1} * (I + dt/2*A) is the Cayley
%   transform of A. When A is skew-symmetric, the Cayley transform is
%   EXACTLY ORTHOGONAL (M'*M = I), so ||C^{n+1}||_2 = ||C^n||_2 to
%   machine precision -- discrete energy is conserved exactly, for ANY
%   time step size (no CFL restriction on stability). Adding the
%   symmetric negative-semidefinite diffusion operator makes the scheme
%   correctly *dissipative* instead of perfectly conserving (as it
%   physically should be), while remaining unconditionally stable.
%
% Author: Generated by Claude
% -------------------------------------------------------------------

clear; clc; close all;

%% ------------------- User-defined parameters -----------------------
L  = 2.0;          % domain length [m] (periodic: point L is identified with 0)
N  = 200;          % number of grid points

% D  = 0.01;         % diffusion coefficient [m^2/s]
D  = 0;         % diffusion coefficient [m^2/s]
u  = 1.0;          % advection velocity [m/s]

T_final = 2.0;     % total simulation time [s]
% dt = 0.01;         % time step [s] -- can be chosen freely for stability;
% dt = 0.001;         % time step [s] -- can be chosen freely for stability;
                    % (accuracy still degrades if dt is too large)

plot_every = 20;    % plot update frequency (in time steps)

%% ------------------- Grid setup (periodic) -----------------------------
x  = linspace(0, L, N+1); x(end) = [];   % N points on [0, L)
dx = x(2) - x(1);

dt = .5*dx;

%% ------------------- Initial condition ----------------------------------
x0 = 0.5*L;
sigma = 0.08*L;
% C0 = exp(-((x - x0).^2) / (2*sigma^2))';   % column vector, N x 1
C0 = exp(-(16*(x - x0).^2) / (2*sigma^2))';   % column vector, N x 1
% C0 = zeros(N,1); C0(1) = 1;   % column vector, N x 1
C  = C0;

Nt = round(T_final/dt);

fprintf('Grid: N = %d points, dx = %.4g\n', N, dx);
fprintf('dt = %.4g, Nt = %d steps, T_final = %.4g\n', dt, Nt, dt*Nt);

%% ------------------- Assemble periodic operator matrices -----------------
% D1: central-difference first derivative, periodic, skew-symmetric
%     (D1*C)_i = (C_{i+1} - C_{i-1}) / (2*dx)
e = ones(N,1);
D1 = spdiags([-e e], [-1 1], N, N) / (2*dx);
D1(1, N)   = -1/(2*dx);   % wrap: node before index 1 is index N
D1(N, 1)   =  1/(2*dx);   % wrap: node after index N is index 1

% D2: central-difference second derivative, periodic, symmetric
%     (D2*C)_i = (C_{i+1} - 2*C_i + C_{i-1}) / dx^2
D2 = spdiags([e -2*e e], [-1 0 1], N, N) / dx^2;
D2(1, N) = 1/dx^2;
D2(N, 1) = 1/dx^2;

% Sanity checks (uncomment to verify skew-/symmetry properties):
% disp(full(D1 + D1'))   % should be ~0 (skew-symmetric)
% disp(full(D2 - D2'))   % should be ~0 (symmetric)

%% ------------------- Full spatial operator A ----------------------------
% dC/dt = A*C ,   A = -u*D1 + D*D2
A = -u*D1 + D*D2;

%% ------------------- Energy-conserving (Crank-Nicolson) time stepping ----
I = speye(N);
M_left  = I - (dt/2)*A;   % implicit part
M_right = I + (dt/2)*A;   % explicit part

% Factorize the (constant) left-hand matrix once for efficiency
[Lf, Uf, Pf, Qf] = lu(M_left);

energy = zeros(Nt+1, 1);
time   = (0:Nt)*dt;
energy(1) = 0.5*dx*sum(C.^2);   % discrete L2 "energy"

figure('Color','w','Position',[100 100 900 650]);

X_C = zeros(N,Nt);

for n = 1:Nt

    rhs = M_right*C;
    % Solve M_left * C_new = rhs  using the precomputed LU factors
    C = Qf * (Uf \ (Lf \ (Pf*rhs)));

    X_C(:,n) = C;

    energy(n+1) = 0.5*dx*sum(C.^2);

    if mod(n, plot_every) == 0 || n == Nt
        subplot(2,1,1);
        plot(x, C0, 'r--', 'LineWidth', 1.2); hold on;
        plot(x, C, 'b-', 'LineWidth', 1.8); hold off;
        xlabel('x'); ylabel('C');
        title(sprintf('1D Advection-Diffusion (periodic, energy-conserving CN),  t = %.3f s', n*dt));
        legend('Initial condition', 'Current field', 'Location', 'northeast');
        % ylim([min(0,min(C0)) max(C0)*1.1]);
        grid on;

        subplot(2,1,2);
        plot(time(1:n+1), energy(1:n+1), 'r-', 'LineWidth', 1.5);
        xlabel('t'); ylabel('Energy  =  0.5 \int C^2 dx');
        title('Discrete energy vs time');
        grid on;
        drawnow;
    end
end

fprintf('Initial energy = %.6g\n', energy(1));
fprintf('Final energy   = %.6g\n', energy(end));
fprintf('(With D = 0 these should match to machine precision;\n');
fprintf(' with D > 0, energy should decay monotonically.)\n');

%% construct ROM basis via POD
[V,S,~] = svd(X_C,'econ');
% n = 14;
% n = 24;
n = 40;
Vn = V(:,1:n);

%% singular value decay
figure
semilogy(diag(S)/S(1,1))
title("singular value decay")

%% state plots
X_b = X_C;
figure; hold on
plot(X_b(:,1))
plot(X_b(:,2))
plot(X_b(:,3))
plot(X_b(:,5))
plot(X_b(:,10))
plot(X_b(:,100))
plot(X_b(:,end))