%% 1D Pure Advection: Illustrating the Theoretical 1/sqrt(n) Singular Value Decay
%
% Demonstrates a well-known result from the reduced-order modeling
% literature (Ohlberger & Rave 2015; Greif & Urban 2019, "Decay of the
% Kolmogorov N-width for wave problems"): for a discontinuous
% ("top-hat"/square-wave) profile transported periodically, the
% singular values of the snapshot matrix decay only algebraically, with
% envelope  sigma_n ~ C/sqrt(n)  -- in sharp contrast to the exponential
% decay typical of smooth or diffusive problems (recall the earlier
% discussion on tuning advection-diffusion setups for slow POD decay).
%
% To isolate this PURELY TRANSPORT-DRIVEN phenomenon from any numerical
% scheme artifacts (dispersion, dissipation, Gibbs ringing from a
% finite-difference solver -- see the earlier discussion of Godunov's
% theorem), this script advances the advection equation using its EXACT
% solution on a periodic grid:
%
%       C(x,t) = C0( x - u*t  mod L )
%
% realized as an exact integer-pixel circshift of the initial profile,
% so every "snapshot" is the exact solution of  dC/dt + u*dC/dx = 0,
% with zero discretization error.
%
% NOTE ON PARAMETER CHOICE: the clean 1/sqrt(n) envelope is the
% asymptotic behavior of the CONTINUOUS translation manifold
% {C0(.-u t) : t in [0,T]}. To see it numerically you want the spatial
% grid to be well-resolved (Ngrid large) relative to the number of
% snapshots (Nsnap moderate) -- i.e. many more spatial DOFs than time
% samples. If you instead take Nsnap = Ngrid with a shift of exactly 1
% cell per snapshot, the snapshot matrix becomes an exact circulant
% matrix and its singular values are just the magnitudes of the DFT of
% C0, which decay like 1/n (faster, and a different phenomenon) --  a
% good example of how the discrete experiment can quietly change what
% it's actually measuring if the sampling ratio isn't chosen carefully.
%
% Author: Generated by Claude
% -------------------------------------------------------------------

clear; clc; close all;

%% ------------------- Parameters ---------------------------------------
L      = 1.0;      % domain length (periodic)
Ngrid  = 2048;      % spatial grid points (fine, to resolve the jump well)
u      = 1.0;       % advection speed
Nsnap  = 128;       % snapshots taken over ONE FULL PERIOD T = L/u
                     % (kept << Ngrid -- see note above)
w      = 0.1*L;      % width of the top-hat (indicator) pulse

assert(mod(Ngrid, Nsnap) == 0, ...
    'Ngrid must be divisible by Nsnap so each snapshot shift is an exact number of grid cells.');
shift_per_snap = Ngrid / Nsnap;

%% ------------------- Grid and initial condition -------------------------
dx = L/Ngrid;
x  = (0:Ngrid-1)'*dx;

xc = 0.5*L;
dist = mod(x - xc + L/2, L) - L/2;    % periodic (shortest) distance to center
C0 = double(abs(dist) < w/2);          % top-hat / indicator pulse

%% ------------------- Generate exact snapshots via periodic shifting ------
% C(:,k) is the EXACT solution at t = (k-1)*T/Nsnap, obtained by
% circularly shifting C0 by (k-1)*shift_per_snap grid cells.
Xsnap = zeros(Ngrid, Nsnap);
for k = 1:Nsnap
    Xsnap(:,k) = circshift(C0, (k-1)*shift_per_snap);
end

t_period = L/u;
fprintf('Grid points: %d, snapshots: %d (one full period T = %.4g)\n', Ngrid, Nsnap, t_period);

%% ------------------- Singular value decomposition -------------------------
[~, S, ~] = svd(Xsnap, 'econ');
sigma = diag(S);
sigma = sigma / sigma(1);      % normalize: sigma(1) = 1

n = (1:numel(sigma))';

%% ------------------- Fit the observed decay rate ---------------------------
% Fit sigma_n ~ C*n^p over a mid-range window (avoid pre-asymptotic small
% n and the very tail, which is limited by finite Ngrid/Nsnap).
fit_range = round(0.1*Nsnap) : round(0.7*Nsnap);
p = polyfit(log(n(fit_range)), log(sigma(fit_range)), 1);
fprintf('Fitted decay exponent p = %.3f  (theory predicts p = -0.5)\n', p(1));

%% ------------------- Compare against theoretical 1/sqrt(n) envelope -------
ref = 1./sqrt(n);

figure('Color','w','Position',[100 100 950 420]);

subplot(1,2,1);
plot(x, C0, 'LineWidth', 1.5); grid on;
xlabel('x'); ylabel('C_0(x)');
title('Initial condition (top-hat pulse)');
ylim([-0.1 1.1]);

subplot(1,2,2);
loglog(n, sigma, 'o', 'MarkerSize', 4, 'LineWidth', 1); hold on;
loglog(n, ref, 'r--', 'LineWidth', 1.5);
loglog(n, exp(polyval(p,log(n))), 'k:', 'LineWidth', 1.2);
grid on; xlabel('mode index n'); ylabel('\sigma_n / \sigma_1');
title('Singular value decay vs. theoretical 1/\surd n');
legend('Snapshot SVD', '1/\surd n reference', ...
       sprintf('fit: n^{%.2f}', p(1)), 'Location', 'southwest');
xlim([1 Nsnap]);

fprintf('sigma_n at n=%d: %.4e   (1/sqrt(n) reference: %.4e)\n', ...
        Nsnap, sigma(end), ref(end));